### ISSUE TITLE
`fetchival.fetch` throws an `Illegal invocation` error

### ISSUE THREAD

**Issue by leonderijke** [typicode/fetchival#1]
Tested in Chrome 42, which has native support for fetch and ES6 Promises: http://codepen.io/leonderijke/pen/pJjdxj?editors=001

When calling `fetchival('/foo').get()`, `fetchival.fetch` throws an `Illegal invocation` TypeError.

Running the tests in Chrome 42 gives the same result: all tests fail with `TypeError: Illegal invocation`.

**Comment by typicode** [comment]
Thanks for raising this issue.
Should be good with v0.1.2

fetch wasn't called with the right context. I've added `.bind(window)`

**Comment by leonderijke** [comment]
Yes, confirming that this error is fixed. Thanks!
